theme:
  name: material
  palette:
    primary: 'deep-purple'
    accent: 'orange'
  feature:
    tabs: true

markdown_extensions:
  - toc:
        permalink: true

nav:
    - Home: index.md
    - Install Guide: install.md
    - FAQ: faq.md
