devtools::use_package('rv')
devtools::use_package('R2WinBUGS')
devtools::use_package('Luminescence')
usethis::use_build_ignore("devtools_history.R")
usethis::use_vignette("OSLpack")
devtools::use_package('tcltk')
